config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      resources :episodes, only: [:index, :update, :show, :create]
    end
  end

  resources :episodes, except: :show
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: :show do
    post :regenerate_token
  end
  root 'episodes#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates :number, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
end

app/controllers/api/v1/episodes_controller.rb
class Api::V1::EpisodesController < ActionController::API

  before_action :ensure_authenticated

  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { message: e.message }, status: :not_found
  end

  def index
    @episodes = Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
  end

  def update
    @episode = Episode.find(params[:id])
    if @episode.update params.require(:episode).permit!
      head :no_content
    else
      render json: { message: @episode.errors.messages }, status: :unprocessable_entity
    end
  end

  def create
    @episode = Episode.new params.require(:episode).permit!
    if @episode.save
      head :created
    else
      render json: { message: @episode.errors.messages }, status: :unprocessable_entity
    end
  end

protected

  def ensure_authenticated
    token = request.headers['Authorization'].split('token=').last if request.headers['Authorization'].present?
    head :unauthorized unless User.exists?(token: token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticable
  protect_from_forgery with: :exception
end

app/controllers/concerns/authenticable.rb
module Authenticable
  extend ActiveSupport::Concern

  def ensure_signed_in
    redirect_to new_session_path, notice: 'Unauthorized.' unless signed_in?
  end

  def signed_in?
    current_admin_id.present?
  end

  def current_admin_id
    session[:admin_id]
  end

  def current_admin
    Admin.find current_admin_id
  end

  included do
    helper_method :current_admin
    helper_method :signed_in?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :ensure_signed_in

  def index
    @episodes = Episode.all
  end

  def new
    @episode = Episode.new
  end

  def create
    @episode = Episode.new(episode_params)
    if @episode.save
      redirect_to episodes_url, notice: 'Episode was successfully created.'
    else
      render :new
    end
  end

  def edit
    @episode = Episode.find(params[:id])
  end

  def update
    @episode = Episode.find(params[:id])
    if @episode.update(episode_params)
      redirect_to episodes_url, notice: 'Episode was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy
    redirect_to episodes_url, notice: 'Episode was successfully destroyed.'
  end

private
  def episode_params
    params.require(:episode).permit(:title, :description, :number)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: :destroy

  def new
  end

  def create
    if admin = Admin.find_by(username: params[:username]).try(:authenticate, params[:password])
      session[:admin_id] = admin.id
      redirect_to episodes_url
    else
      redirect_to new_session_url, notice: 'Username and Password not on file'
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to new_session_url
  end

private

  def ensure_signed_out
    redirect_to root_url if signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_in

  def regenerate_token
    @user = User.find(params[:user_id])
    @user.regenerate_token
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :episode_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :episode_description %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :episode_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.description %></td>
        <td><%= episode.number %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

<footer>
  <br/>
  <%= link_to_if signed_in?, 'Log Out', session_path, method: :delete %>
</footer>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunWatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= @user.attributes %>

<%= button_to 'Regenerate Token', user_regenerate_token_path(@user) %>

<footer>
  <br/>
  <%= link_to_if signed_in?, 'Log Out', session_path, method: :delete %>
</footer>